version: "3"

networks: 
    backend:
        driver: bridge

services: 
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        volumes: 
            - ./:/var/www:cached
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/logs:/var/log/nginx:cached
        ports: 
            - ${DOCKER_HTTP_PORT}:80
            - ${DOCKER_HTTPS_PORT}:443
        networks: 
            - backend

    php-fpm:
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes: 
            - ./:/var/www:cached
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/logs:/var/log/php:cached
        expose: 
            - 9000
        networks: 
            - backend

    mysql:
        build: 
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        environment: 
            - MYSQL_DATABASE=mysql
            - MYSQL_USER=${DOCKER_MYSQL_USER}
            - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
        volumes: 
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports: 
            - ${DOCKER_MYSQL_PORT}:3306
        networks: 
            - backend